### ISSUE TITLE
This is not even working on phone or any simulator,

### ISSUE THREAD

**Issue by ShailendraKushwaha** [pmusolino/Wormholy#107]
I just added it to my project. and nothing else,
are there any more steps to get it working,
cant find it in readme

**Comment by pmusolino** [comment]
Hi there. 
If you make a shake within your app, does Wormholy appear?

**Comment by pmusolino** [comment]
I released a new (big) version of Wormholy (1.6.5) with some improvements and fixes. https://github.com/pmusolino/Wormholy/releases/tag/1.6.5 Can you test it and let me know if you are still encountering this issue?

**Comment by ShailendraKushwaha** [comment]
No , it did not appear when i shake device or simulatore within my app. i wil test again and let you know. thanks
