### ISSUE TITLE
Need to customise Share Strings

### ISSUE THREAD

**Issue by pratik-gits** [pmusolino/Wormholy#119]
I need to customise few strings such as Share as cURL string. So, what should be the way ahead? I have two solutions -
1. I make a separate branch in your repository, and use that.
2. Fork it at my org's end and use it from there.

What do you guys suggest?

**Comment by pmusolino** [comment]
Hi there. Sorry for the late reply. From my understanding, you want to customize the Share as a cURL string inside Wormholy? If so, you should use a fork, as this is outside the scope of what Wormholy was designed for.
