### ISSUE TITLE
Can't disable shake gesture

### ISSUE THREAD

**Issue by kapoorsahil** [pmusolino/Wormholy#12]
Setting`WORMHOLY_SHAKE_ENABLED` to `NO` in environment variables doesn't work for me.

Xcode 9.4.1
iOS 11.4.1

**Comment by pmusolino** [comment]
It's really strange. I tested it now, and it works.

Do you insert `WORMHOLY_SHAKE_ENABLED` in the right place?

<img width="906" alt="schermata 2018-07-24 alle 10 01 53" src="https://user-images.githubusercontent.com/495617/43124901-c05d0ffe-8f28-11e8-8086-cf41815664d3.png">

**Comment by davedelong** [comment]
It'd be nice if this were runtime-configurable
