### ISSUE TITLE
Ability to filter by status code

### ISSUE THREAD

**Issue by cedricbahirwe** [pmusolino/Wormholy#122]
## General question and Feature request
I was wondering if it could be helpful to have the ability to filter the requests' responses by (for example their `Status Code`) so you don't have to scroll a lot in order to get to a request with a specific status code.

**Comment by pmusolino** [comment]
This is a good suggestion. Added between the future enhancement. 👍

**Comment by pmusolino** [comment]
Since I'm launching Wormholy 2 soon, which is a major rewrite of the library, it wasn't possible to merge this PR. However, I took your suggestion and integrated it here: 6b3990487f5fe628e1c23e035a9020900579a882.
