### ISSUE TITLE
Network traffic statistics

### ISSUE THREAD

**Issue by akovalov** [pmusolino/Wormholy#123]
I was wondering if Wormholy records all app traffic, is it possible to get data size statistics like how many bytes sent received (zipped and unzipped) and timing per each request? Thanks!

**Comment by FarooqMulla** [comment]
I started using URLSessionTaskTransactionMetrics and collected all the statistics and displayed under Overview section. Here is the URL with details: https://developer.apple.com/documentation/foundation/urlsessiontasktransactionmetrics

[https://github.com/pmusolino/Wormholy/pull/143](https://github.com/pmusolino/Wormholy/pull/143)

**Comment by pmusolino** [comment]
Hi there. I applied all these improvements in this commit 89469653ce4ca39a436cf530c85f27259e8360f8, which will be merged soon and released with Wormholy 2.

**Comment by akovalov** [comment]
@pmusolino great, thanks! Have you checked if `countOfResponseBodyBytesReceived` and other size parameters are provided by the system in case `Transfer-Encoding: chunked` in the response? From my experience using `URLSessionTaskTransactionMetrics` it doesn't provide it, probably with other transfer encoding it works ok.

**Comment by pmusolino** [comment]
@akovalov I didn't, because unfortunately, it's not easy to test all these edge-case without a backend as support. But if you want, you can try by yourself if it works properly in this branch: `feat/swift-ui-ios-15-support`

**Comment by akovalov** [comment]
@pmusolino Just FYI Wormholy Stats screen shows received compressed responses size with chunked transfer encoding, so all looks good. Thank you!
