### ISSUE TITLE
Search Result on Response Body and Request Body screen not visible on darkmode.

### ISSUE THREAD

**Issue by affanhasby** [pmusolino/Wormholy#128]
Description : 
When doing search in Response/Request Body, the text is not visible because text color blend with background color. 

Step to reproduce :
1. Make sure you're running in Darkmode.
2. Shake Apps to trigger wormholy screen.
3. Tap one of API listed there.
4. Tap Request Body or Response Body.
5. Search a keyword on search bar.
6. Your Screen only show matched keyword, other text is not visible (see screenshoot below)

Screenshoot issue :
![image (12) (1)](https://user-images.githubusercontent.com/38319387/205271158-39c2ac87-8017-406f-baaa-34fd6e5dad83.png)

**Comment by rickirby** [comment]
hi @pmusolino is there any update for this issue? I've made PR for the fix here https://github.com/pmusolino/Wormholy/pull/129

**Comment by pmusolino** [comment]
Merged :shipit:
