### ISSUE TITLE
Responses are not cached in CustomHTTPProtocol

### ISSUE THREAD

**Issue by Jyothi-Narayan** [pmusolino/Wormholy#135]
Cache storage policy is not set as per the caching policy in URLRequest received.
When the url request cache policy is `NSURLRequestReturnCacheDataElseLoad` , as per the below code storage policy is set to `URLCache.StoragePolicy.notAllowed`

```
public func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive response: URLResponse, completionHandler: @escaping (URLSession.ResponseDisposition) -> Void) {
        let policy = URLCache.StoragePolicy(rawValue: request.cachePolicy.rawValue) ?? .notAllowed
        client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: policy)
        currentRequest?.initResponse(response: response)
        completionHandler(.allow)
    }
```

And it doesn't skip the api call when the url request policy is set to load from cache

```
override public class func canInit(with request: URLRequest) -> Bool {
        guard CustomHTTPProtocol.shouldHandleRequest(request) else { return false }

        if CustomHTTPProtocol.property(forKey: Constants.RequestHandledKey, in: request) != nil {
            return false
        }
        return true
    }
```

the above `canInit` func only ignores the request which are from ignored hosts, doesn't ignore the requests with cache policy set to `NSURLRequestReturnCacheDataElseLoad`/ `NSURLRequestReturnCacheDataDontLoad`

**Comment by pmusolino** [comment]
I applied those changes here: 2f4265e1af43f45c2850f2e909921cea42aeeb41. Please let me know if you find anything unusual.
