### ISSUE TITLE
Wormholy with Alamofire SPM

### ISSUE THREAD

**Issue by PeHk** [pmusolino/Wormholy#136]
I am using Alamofire latest package through Swift Package Manager -> on login request I am trying to catch redirects (status code 302).

Without Wormholy installed everything works as expected. After adding Wormholy to the project I am unable to catch redirects. Anyone have the same issue?

**Comment by nalthenayan** [comment]
I'm facing the same issue

**Comment by pmusolino** [comment]
I'm sorry for the late reply. Could you explain what you're trying to do, maybe with some example code? Do these redirect requests appear in Wormholy?

**Comment by pmusolino** [comment]
Guys, the new release 2.0.0 that support also SPM is online! [Check it out now](https://github.com/pmusolino/Wormholy/releases/tag/2.0.0). Please, check if, with this latest update, everything works as expected. Closing this issue for now.
