### ISSUE TITLE
Wormholy with SPM on XCode 15

### ISSUE THREAD

**Issue by fiteroc** [pmusolino/Wormholy#139]
Wormholy is not working with SPM on Xcode 15! I have tried to add the latest version(1.7.0) and then went back until 1.5.0 but it always gives the same error: "Source files for target Wormholy should be located under 'Sources/Wormholy', or a custom sources path can be set with the 'path' property in Package.swift. Unexpectedly did not find the new dependency in the package graph: sourceControl". Please fix the package issue so the library can be added via SPM.

**Comment by pmusolino** [comment]
We're working on it: https://github.com/pmusolino/Wormholy/pull/116

**Comment by siki88** [comment]
what is the status?

**Comment by pmusolino** [comment]
@siki88 just asked to the author of the PR

**Comment by pmusolino** [comment]
The [new release 2.0.0](https://github.com/pmusolino/Wormholy/releases/tag/2.0.0) that support SPM is online!
