### ISSUE TITLE
CocoaPods can not find specification

### ISSUE THREAD

**Issue by mkeremkeskin** [pmusolino/Wormholy#15]
Hi there,

I'm trying to use the library via CocoaPods but it gives the error below. 

> [!] Unable to find a specification for `Wormholy`

Maybe something got broken in latest version of .podspec file. 

Thnx already.

**Comment by pmusolino** [comment]
Hi @mkeremkeskin ,

before `pod install`, try to call `pod repo update` for updating your local specs.

From one of the last release of cocoapods, `pod repo update` is no longer automatically called.

-Paolo
