### ISSUE TITLE
Blocking Progress Update while uploading or downloading a file.

### ISSUE THREAD

**Issue by Abdallah-Shaheen** [pmusolino/Wormholy#24]

**Comment by pmusolino** [comment]
Hi,
what do you mean? Can you show me something?

Thanks
-Paolo

**Comment by Abdallah-Shaheen** [comment]
Hi Paolo and Thank you
the problem is when I try to upload or download file I need to update UI progress with Wormholy the progress update is blocked when I uninstalled Wormholy the UI progress update work again.

Thanks
Abdallah Shaheen
![img_0012](https://user-images.githubusercontent.com/22009198/43470997-40ecd71e-94ea-11e8-8943-9fa9d89191b3.JPG)

**Comment by pmusolino** [comment]
It's really strange. Can you send me a simple demo project where I can replicate the problem?

**Comment by kingsofteng** [comment]
I guess this is an issue related to updating UI on the non-main thread.
@Abdallah-Shaheen 
It would be helpful if you provide the detailed information or simple demo project.
Then I can help you.
