### ISSUE TITLE
Is it compatible with Moya ? 

### ISSUE THREAD

**Issue by Chirag1992** [pmusolino/Wormholy#27]

**Comment by pmusolino** [comment]
If it uses NSURLSession yes! I see that Moya is an abstraction layer on top of Alamofire, then YES, Wormholy works.

**Comment by Chirag1992** [comment]
But it is not working.. do we have to write any code for this .. because I just integrated the sdk .

**Comment by pmusolino** [comment]
What version do you have integrated? Using Cocoapods?

**Comment by Chirag1992** [comment]
(1.1.0) yes through cocoa pods

**Comment by pmusolino** [comment]
Try the new release `1.1.2`, that fix the problem. 

Before `pod install`, try to call `pod repo update` for updating your local specs.

- Paolo

**Comment by Chirag1992** [comment]
still its working after updating pod

**Comment by pmusolino** [comment]
The Wormholy's view appear, right?

**Comment by Chirag1992** [comment]
![img_a7d20135f0fb-1](https://user-images.githubusercontent.com/34506147/43524609-c2ceb222-95b0-11e8-8ef4-13a21c97a3bd.jpeg)
I got this.. this also I got earlier also

**Comment by pmusolino** [comment]
What is this?

**Comment by Chirag1992** [comment]
after shaking phone I got this screen

**Comment by pmusolino** [comment]
I think that you are using another library or there is something else in your code that uses the shake gesture. Try to fire Wormholy manually using

`NotificationCenter.default.post(name: NSNotification.Name(rawValue: "wormholy_fire"), object: nil)` 

Please, read the **Usage** section in the README.

-Paolo

**Comment by Chirag1992** [comment]
no its not working

**Comment by pmusolino** [comment]
Do you have the "debug" configuration in your project?

The screen that you posted is not Wormholy ¯\_(ツ)_/¯ then, there is something that prevents Wormholy to be presented.

**Comment by Chirag1992** [comment]
yes debug configuration is there in the project

**Comment by pmusolino** [comment]
Even if it does not work with Moya, the library must be able to appear. The fact that it does not appear to you, means that there is something that prevents it from doing so. Do you have anything in the console?

**Comment by Chirag1992** [comment]
ya the screen shot I share was our screen . now wen remove the shake of our that screen. But now after shake wormhole screen is not coming. I am in debug mode only

**Comment by pmusolino** [comment]
It is difficult to understand why this happens. Try to make a small demo project where you can reproduce the problem, so I can investigate.
