### ISSUE TITLE
Filter requests for a specific domain and Ability to clear the requests log

### ISSUE THREAD

**Issue by mohammad19991** [pmusolino/Wormholy#28]
Currently `Wormholy` will log all the network calls that uses `NSURLSession` so you will see many requests being triggered by third party SDKs which I don't want always to see but I would like to see all the requests related to my domain.

Also it would be nice if we can clear the log.

**Comment by pmusolino** [comment]
You can search for the API calls you need, but the functionality to clean the calls you made earlier is useful! I will implement it as soon as possible.

**Comment by dwdmarkowski** [comment]
Could I implement cleaning calls? :)
