### ISSUE TITLE
I want to integrate to custom schemes

### ISSUE THREAD

**Issue by Pulkit-1mg** [pmusolino/Wormholy#35]
I have 4 schemes in my project except Release and I want to integrate in all the schemes  except Release version.

Can anyone please explain the steps required to achieve my requirement?

Thanks in advance

**Comment by Pulkit-1mg** [comment]
Also if I remove my debug build configuration, then library is not working on any scheme.

**Comment by pmusolino** [comment]
Hi @Pulkit-1mg,

do you use NSURLSession or a library for the network requests?

**Comment by Pulkit-1mg** [comment]
we are using AFNetworking. But I also tried this in an empty project. This is only working with a project with existing Debug scheme, if I delete Debug scheme this stops working.

Also one more scenario I found where my app stops working, After making an API call to upload an image my app stops making any api call (This occurs only if Wormholy is enabled).

Please let me know ho to solve this

**Comment by pmusolino** [comment]
This could be a bug. Can you pass the demo project?
You can try to integrate Wormholy in any scheme, using only

```
pod 'Wormholy'
```

Before a `pod update`, try to call `pod repo update`.

-Paolo

**Comment by Pulkit-1mg** [comment]
Please find the sample project
https://drive.google.com/open?id=1KZJbhr0yi5_bT66cEw9vqbcYdfZ_ZLzm

In the project I have only Staging in my Podfile. But library is not working.

Please let me know hot to resolve this.

**Comment by Pulkit-1mg** [comment]
Hi @pmusolino 
Found an issue with library.
After making an api call which is a POST request with multi-part content. Every next API call results into timeout.

Please suggest a  resolution for this?

**Comment by pmusolino** [comment]
I have to investigate this. Can you open a new issue not related to this? Thanks
