### ISSUE TITLE
Allow sharing whole network session and whole request

### ISSUE THREAD

**Issue by ilyapuchka** [pmusolino/Wormholy#37]
Quickly skimming through code I didn't fine anything indicating that this is currently possible and screenshots in README also prove that. Would be nice to be able to share not just individual screenshots but the whole network session, in a for of archive probably. As well as individual request completely, not just its body and response body.
I'm cloning the project now to see if I can add this.
Looking forward to integrate this in my current project!

**Comment by pmusolino** [comment]
This could be interesting! 
I have to think about how to implement it, and especially in what format.

**Comment by pmusolino** [comment]
Implemented in this new release: https://github.com/pmusolino/Wormholy/releases/tag/1.2.1 Now you can copy or save requests in `.txt`.
