### ISSUE TITLE
Getting timeout for every api call after making a multi-part api call 

### ISSUE THREAD

**Issue by Pulkit-1mg** [pmusolino/Wormholy#38]
Found an issue with library.

After making an api call which is a POST request with multi-part content. Every next API call results into timeout.

Please suggest a resolution for this?

**Comment by pmusolino** [comment]
If you have any useful code to replicate the problem, feel free to post it here.

**Comment by pmusolino** [comment]
Fixed here https://github.com/pmusolino/Wormholy/pull/92
