### ISSUE TITLE
UIWebView 302 Redirects cause duplicate requests

### ISSUE THREAD

**Issue by alpriest** [pmusolino/Wormholy#40]
When using Wormholy, a UIWebView that receives a 302 Redirect response issues 2 requests for the redirect URL. You can see it happening by monitoring the web requests in Charles. This does not happen with WKWebView but there is a bug with that implementation which means I have to use UIWebView for now.

I've attached a sample project which demonstrates the failing behaviour, and also screenshots illustrating the duplicate request.

Without Wormholy installed:
<img width="812" alt="screen shot 2018-08-30 at 15 07 10" src="https://user-images.githubusercontent.com/221241/44857507-de8a1380-ac67-11e8-9c78-22329257c251.png">

With Wormholy installed
<img width="817" alt="screen shot 2018-08-30 at 15 10 33" src="https://user-images.githubusercontent.com/221241/44857509-de8a1380-ac67-11e8-9bc1-2395004406d0.png">

[Wormholy-WebView-Duplicate-Request-Example.zip](https://github.com/pmusolino/Wormholy/files/2336526/Wormholy-WebView-Duplicate-Request-Example.zip)

**Comment by pmusolino** [comment]
This is really strange. I will investigate.

**Comment by yangfeiyu** [comment]
I meet too

**Comment by fvvliet** [comment]
Any updates on this ?

**Comment by pmusolino** [comment]
I released a new (big) version of Wormholy (1.6.5) with some improvements and fixes. https://github.com/pmusolino/Wormholy/releases/tag/1.6.5 Can you test it and let me know if you are still encountering this issue?

**Comment by alpriest** [comment]
This is still an issue with 1.6.5.

As `UIWebView` was deprecated in iOS 12.0 I tested with `WKWebView` and it is does not occur with that.
