### ISSUE TITLE
Capture output to an external service

### ISSUE THREAD

**Issue by richardtop** [pmusolino/Wormholy#41]
I have an idea to be able to capture the i/o of the networking stack and to share it automatically to some server. Or, at least, be able to share all the captured information as archive.

**Comment by pmusolino** [comment]
I believe I could expose the model of requests. I put your proposal in the list of improvements.

**Comment by richardtop** [comment]
@pmusolino maybe, utilize Apple's `OSLog` somehow?

**Comment by richardtop** [comment]
@pmusolino I was thinking of somehow utilizing OSLog to capture output and send it to the remote location. But now I think, it's better to have some custom solution.

The goal is to be able to debug networking from user's devices which are not onsite.

**Comment by pmusolino** [comment]
I agree. The only solution is to create a web service. For the moment, the fastest solution is to expose requests, so that the developer can do what he wants.

**Comment by richardtop** [comment]
What you mean is to add an option to expose requests, so the developer could plug in its own module tied to a web service?

I was thinking about even simpler case - to store the data locally and share with the iOS default dialog
![image](https://user-images.githubusercontent.com/8013017/46141043-7f65f180-c25b-11e8-946c-8b6cd5f8caf6.png)

**Comment by pmusolino** [comment]
@richardtop yes to everything. 

Linked topic: https://github.com/pmusolino/Wormholy/issues/37

**Comment by richardtop** [comment]
Both approaches would be highly appreciated. In essence, you could use the interface to plug in your own share extension.

**Comment by pmusolino** [comment]
Yes, but the big question mark is the sharing format. Can a simple appropriately formatted text file be enough? What may be the use cases in your opinion?

**Comment by richardtop** [comment]
Let's take my use-case, for example.
My app has an issues only with one particular user with one particular phone. I'd like to send him a custom build and ask to do certain actions. Then, he sends me the archive back, so I could trace, which requests succeeded and which failed.

The problem is that I can't just take that user's phone and connect it to a debugger, as he is in different location.

**Comment by pmusolino** [comment]
Your use case is clear. Ok, I'll work in the next few days.
Stay tuned.

**Comment by pmusolino** [comment]
Implemented in this new release: https://github.com/pmusolino/Wormholy/releases/tag/1.2.1 Now you can copy or save requests in .txt. Also, requests are exposed to the developer.
