### ISSUE TITLE
Wormholy not being presented in certain cases

### ISSUE THREAD

**Issue by dimitris-c** [pmusolino/Wormholy#44]
Currently if a UIViewController has presented a modal, Wormholy is unable to get presented.

I made a PR #43 to fix this by recursively checking the presentedViewController

**Comment by pmusolino** [comment]
Hi, @dimitris-c thanks for your PR!

I don't understand why you do this. In every case that I tested, Wormholy is presented in the right way, also if the view controller how present Wormholy is presented as a modal.

What is your use case?

**Comment by dimitris-c** [comment]
In my case, I use the library as part of a Debug menu, not as a standalone. 
In my case I had two modally presented view controllers, and Wormholy couldn't be presented.

**Comment by pmusolino** [comment]
PR merged, thanks @dimitris-c
