### ISSUE TITLE
iPhone X Layout issue

### ISSUE THREAD

**Issue by nomimalik1769** [pmusolino/Wormholy#54]
iphone X layout issue it's showing black screen on top I am attaching screenshots. I am using latest version of Wormholy.
![03A21C10-F4F6-4D4E-9487-F015412017FA](https://user-images.githubusercontent.com/26509387/54434028-1877be80-474f-11e9-8248-612fa4ec4164.jpg)
![A1A09CB1-41C5-441E-9DA4-5583DBD39794](https://user-images.githubusercontent.com/26509387/54434029-1877be80-474f-11e9-9307-1d1a74495887.jpg)

**Comment by pmusolino** [comment]
This is really really strange. Do you use one or more library that has interference with the UI?
Which iOS version do you use?

**Comment by nomimalik1769** [comment]
I am using iOS version 11
and Only Wormholy is creating this strange issue.

**Comment by pmusolino** [comment]
Can you send me a demo project where the problem occurs?

**Comment by pmusolino** [comment]
Closed due to inactivity.
