### ISSUE TITLE
'Wormholy-Swift.h' file not found

### ISSUE THREAD

**Issue by jihongboo** [pmusolino/Wormholy#57]
I can run my App in my device or simulator, but when I try to archive, I got a "'Wormholy-Swift.h' file not found" message.

**Comment by pmusolino** [comment]
Are you using `use_modular_headers!` in your podfile?

**Comment by jihongboo** [comment]
No. And it seems like a random events. I have tried clean build Folder, reinstall Wormholy, but sometimes it works fine, sometimes it just can't make it.
![29301556619278_ pic_hd](https://user-images.githubusercontent.com/15397647/56955567-60726980-6b74-11e9-8cea-2ad1b1cdea9f.jpg)

**Comment by pmusolino** [comment]
I'm really sorry for the delay, I didn't realize you were waiting for an answer, and I imagine you have already solved the problem.
Let me know if you solved. Thanks
