### ISSUE TITLE
wormholy don't show when  I   also   override var next: UIResponder

### ISSUE THREAD

**Issue by ZackKingS** [pmusolino/Wormholy#59]
extension UIApplication {
    private static let invokeAwakeTestOnce: Void = {
        SwiftAwakeFactory.awakeAllClass()
    }()

    open override var next: UIResponder? {
        UIApplication.invokeAwakeTestOnce
        return super.next
    }
}

**Comment by pmusolino** [comment]
Probably you broke the shake. If you declare a new shake action, and you override UIResponder, your method linked to you shake action is called?
