### ISSUE TITLE
Swift 5 Compiler Error 

### ISSUE THREAD

**Issue by silnose** [pmusolino/Wormholy#60]
Situation: First try installing Wormholy in my app

Result after:
/Pods/Wormholy/Sources/Subclasses/WHBaseViewController.swift:44:91: 'shared' is unavailable: Use view controller based solutions where appropriate instead. 
1. 'shared' has been explicitly marked unavailable here (UIKit.UIApplication)

**Comment by pmusolino** [comment]
Hum... can you try to clean the project and derived data please?

**Comment by rayray** [comment]
Same, this doesn't seem to work at all in Xcode 10.3 with Cocoapods. Fresh `pod install`, cleaned build folder. The Wormholy target is set to Swift 4.0, but there are still a lot of errors about renamed APIs.

**Comment by pmusolino** [comment]
Hi there. Are you sure are you using the latest version of Wormholy (v.1.4.1)?
