### ISSUE TITLE
Disables SSLPinning on Alamofire

### ISSUE THREAD

**Issue by devturhan** [pmusolino/Wormholy#62]
Wormholy overriding certificate pinning options while using with Alamofire.
I'm using the example code block to pin certificates. While Wormholy enabled, it is not working correctly. 

```
var serverTrustPolicies: [String: ServerTrustPolicy] = [:] 
let trustPolicy = ServerTrustPolicy.pinCertificates(
    certificates: ServerTrustPolicy.certificates(),
    validateCertificateChain: true,
    validateHost: true)

serverTrustPolicies["xxxxx.com"] = trustPolicy

let configuration = URLSessionConfiguration.default

let serverTrustPolicyManager = ServerTrustPolicyManager(policies: serverTrustPolicies)

let sessionManager = SessionManager(
    configuration: configuration,
    serverTrustPolicyManager: serverTrustPolicyManager
)

return sessionManager

**Comment by pmusolino** [comment]
Hi there.
I'm so sorry for the late reply, I had completely lost this issue.

We should investigate further to understand why this happens since I don't know all the dynamics under Alamofire. This is the first time that I see this problem.

**Comment by Unihilator** [comment]
It's not about Alamofire. Wormholy basically doesn't allow to call urlSession(_:didReceive:completionHandler:) delegate method which handles session level challenges. You can reproduce it by simply implement session delegate with the method above.

**Comment by Unihilator** [comment]
Fixed in [this PR](https://github.com/pmusolino/Wormholy/pull/71). Feel free to review

**Comment by mateuszdetko** [comment]
Any update? I have the same issue.

**Comment by quifago** [comment]
any update?

**Comment by pmusolino** [comment]
I still have to look at this issue in detail but if you have time, feel free to contribute ;)
