### ISSUE TITLE
Wormholy is re-enabled when referencing default or ephemeral session configs after being previously disabling

### ISSUE THREAD

**Issue by colinhumber** [pmusolino/Wormholy#69]
If I call the `Wormholy.enable(_:sessionConfiguration:)` to disable logging of network traffic on either the `URLSessionConfiguration.default` or `URLSessionConfiguration.ephemeral`, the next time either of those configurations are referenced, Wormholy will re-enable logging for those configurations as the swizzled accessors in `NSURLSessionConfiguration+Wormholy` automatically enable logging.

As of now, I'm not really sure how to completely disable logging without completely removing the framework.

**Comment by pmusolino** [comment]
Hi there!
Thanks for discovering this bug.
I think I understand where the problem is, but I'm not able to test it.
Do you have a test project, where can I replicate this issue?

**Comment by colinhumber** [comment]
Sure thing. I've attached a project and commented the affected lines in `AppDelegate.swift`.
[wormholytest.zip](https://github.com/pmusolino/Wormholy/files/3794086/wormholytest.zip)

**Comment by volbap** [comment]
Hi there, I had the same issue. I just created a [pull request](https://github.com/pmusolino/Wormholy/pull/101) that hopefully solves it.

**Comment by pmusolino** [comment]
I released a new (big) version of Wormholy (1.6.5) with some improvements and fixes. https://github.com/pmusolino/Wormholy/releases/tag/1.6.5 Can you test it and let me know if you are still encountering this issue?
