### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ValeriiSohlaiev** [pmusolino/Wormholy#70]
Currently, I'm experiencing a spike of memory leaks on my graph every time I use the pod. Thoughts about it?

![Group](https://user-images.githubusercontent.com/2727120/68652398-09d9e500-0532-11ea-831e-55f4517e4ef7.png)

**Comment by pmusolino** [comment]
Hi there.
Which version are you using? We fixed a memory leak in version 1.4.1. Try to install the latest version (1.5.0) and let me know.

Thanks

**Comment by ValeriySoglaev** [comment]
Hi, sorry but I use 1.5.0
<img width="569" alt="image" src="https://user-images.githubusercontent.com/2727120/68797453-51a95b00-065d-11ea-85f9-2b8833a3297b.png">
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/2727120/68797509-6685ee80-065d-11ea-9330-3c46b8b667b5.png">

**Comment by pmusolino** [comment]
I released a new (big) version of Wormholy (1.6.5) with some improvements and fixes. https://github.com/pmusolino/Wormholy/releases/tag/1.6.5 Can you test it and let me know if you are still encountering this issue?
