### ISSUE TITLE
is it possible to make the dev panel more readable in dark mode?

### ISSUE THREAD

**Issue by Alex-k-tech** [pmusolino/Wormholy#72]
is it possible to make the dev panel more readable in dark mode? Turn off the dark mode for the Wormholy dev panel it is also a good solution
for now, it looks like this 
![image](https://user-images.githubusercontent.com/54838534/72243999-560ed780-35fe-11ea-9ad7-35c912c177b7.png)

**Comment by SagarSDagdu** [comment]
@Alex-k-tech , A full fledged dark mode support has been added in #83 . Here is a sample screenshot:
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-24 at 08 07 54](https://user-images.githubusercontent.com/11807135/80169697-c668c400-8603-11ea-8dcd-690d4622fad1.png)

@pmusolino Please review. 😊

**Comment by pmusolino** [comment]
Implemented here https://github.com/pmusolino/Wormholy/pull/83
