### ISSUE TITLE
Using in Objective-C project

### ISSUE THREAD

**Issue by drinkius** [pmusolino/Wormholy#74]
Trying to use the current version 1.5.1 in an old Objective-C project I get an error:

>  `Wormholy` does not specify a Swift version and none of the targets (`xxxx`, `xxxx `) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

The problem is - I don't have such a setting in the project and `post_install` script doesn't work - I don't get to that stage at all so I can't set the version using `Podfile` script.

Is it possible to add the `SWIFT_VERSION` as the warning suggests or is there any other way to install Wormholy without modifying the project much?

**Comment by pmusolino** [comment]
Hi there. It was implemented here https://github.com/pmusolino/Wormholy/pull/79 if you try to use the latest release, you will not see the error.
