### ISSUE TITLE
Unable to open in the Xcode 11.4 Simulators

### ISSUE THREAD

**Issue by jackjpark** [pmusolino/Wormholy#78]
I have upgraded to the latest release of xcode, shake device no longer opens wormhole and neither does using a debug button thats meant to show the pop over.

Has something changed to block wormholy from displaying?

**Comment by pmusolino** [comment]
Hi there! I haven't tested the new version of Xcode yet. I will do it soon.

**Comment by pmusolino** [comment]
@jackjpark I discovered where is the issue. I opened a PR to fix it.
