### ISSUE TITLE
Intercept WKWebView calls

### ISSUE THREAD

**Issue by afallon02** [pmusolino/Wormholy#8]
Would be great (if possible) to enable requests sent via a WKWebView to be intercepted and shown within Wormholy's debug menu.

These resources might help:
1) https://stackoverflow.com/questions/40133512/intercept-request-with-wkwebview
2) https://github.com/BKRApps/KRWebView

**Comment by fvvliet** [comment]
+ 1

**Comment by tommy19970714** [comment]
I made a sample code for WKWebView.
Please check my repository.
https://github.com/tommy19970714/WebKitURLProtocol/tree/master

**Comment by pmusolino** [comment]
@tommy19970714 please, feel free to open a PR. 👍

**Comment by alobaili** [comment]
@tommy19970714 & @pmusolino has this been implemented in Wormholy? If not, I think we should keep this issue opened for possible contributions.

It would also be useful to intercepts SFSafariViewController network for debugging. E.g. if I'm using the [AppAuth-iOS](https://github.com/openid/AppAuth-iOS) and I want to debug what happens in the auth flow inside the Safari view controller.
