### ISSUE TITLE
Wormholy no longer works on iOS 13.4 

### ISSUE THREAD

**Issue by sjapps** [pmusolino/Wormholy#87]
This library no longer works on iOS 13.4 because of how it self loads into the app delegate. 

https://stackoverflow.com/questions/60970783/why-is-the-next-method-of-uiapplication-not-executed-after-ios-13-4

Wormholy uses this `next` method approach and it is no longer allowed (or it is a bug).

**Comment by pmusolino** [comment]
Hi there. This problem should be fixed from release 1.5.2. https://github.com/pmusolino/Wormholy/releases

Did you try to update the library?
