### ISSUE TITLE
Carthage build failure on Xcode 12 beta 2

### ISSUE THREAD

**Issue by TizianoCoroneo** [pmusolino/Wormholy#91]
Building the library with Carthage 0.34.0, using the Xcode 12 beta 2 toolchain, produces a build error that complains about an undefined symbol for architecture armv7. 
```
Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in RequestModel.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This looks like [this same issue](https://developer.apple.com/forums/thread/649918?login=true) reported in the Apple Developer forums. Let's try again in Xcode beta 3 I guess?

**Comment by pmusolino** [comment]
Hi Tiziano. Can you retry with the latest beta of Xcode, please?

**Comment by TizianoCoroneo** [comment]
Tested 1.6.3 with Xcode 12 beta 6. Works 👍
