### ISSUE TITLE
SPM Xcode 

### ISSUE THREAD

**Issue by skychiarottoa** [pmusolino/Wormholy#95]
If I try do import it with SPM i get the follwing:

Source files for target Wormholy should be located under 'Sources/Wormholy', or a custom sources path can be set with the 'path' property in Package.swift

**Comment by tadelv** [comment]
I got the same error. I've forked the project and then found out, that you can't have mixed language packages with SPM, so I made changes to wormholy to be Swift only, while sacrificing the automagic hooks. But it's now pure Swift and uses `Wormholy.awake()` to setup itself.

**Comment by pmusolino** [comment]
For the moment it's not possible to use SPM because of the classes in Obj-C.

**Comment by Sundea** [comment]
I still have this issue 1.6.5 version

**Comment by Moamenzalabia** [comment]
I still have this issue any fix, please? 
Source files for target Wormholy should be located under 'Sources/Wormholy', or a custom sources path can be set with the 'path' property in Package.swift

**Comment by tadelv** [comment]
You can try and use this fork: https://github.com/tadelv/Wormholy
