### ISSUE TITLE
Request body can't be seen again in Wormholy 1.6.3

### ISSUE THREAD

**Issue by San-Di** [pmusolino/Wormholy#97]
Hello,

I am using wormholy in version 1.6.3 and my installation in pod file is  `pod 'Wormholy', :configurations => ['Debug']` for ios version 13 with swift 5.

But yet I still can't see my request body.

Please help me with the issue. And also point if I need extra configuration to set.

Thank you in advanced.

**Comment by pmusolino** [comment]
Hi there. Are you sure that you are using version 1.6.3? Can you run a `pod repo update && pod update`?

**Comment by San-Di** [comment]
Hello @pmusolino ,

Thank you for your quick response. Yes I am using Wormholy (1.6.3) and I also tried pod update and reinstall.

And I'm still not seeing the request body. Do I still need any other configurations?

**Comment by pmusolino** [comment]
Can you try to install the demo app, and see if you are able to see the request body? Are you using Alamofire or URLSession?

**Comment by San-Di** [comment]
Hello,

Yeh, I tried the demo app and still not seeing request body for all API requests, I have no problem with response body though. I am using Alamofire ( 5.4.0 v) for my project.

Here is how I installed Wormholy ` pod 'Wormholy', :configurations => ['Debug']` in podfile for my app.

**Comment by pmusolino** [comment]
Hey @San-Di, I investigated and you was right, there was a bug. 
I fixed it in the latest version 1.6.4. Can you try it?

Thanks

**Comment by NomadicWarrior** [comment]
Hi, I also  installed Wormholy  pod 'Wormholy', :configurations => ['Debug'] in podfile for my app. version: 1.6.6
Alamofire 5.5.0
Can not see the response body. It shows only -
